export const mockPortfolio = {
  hero: {
    bannerImage: '/img/1BMW.jpg',
    tagline: 'Electronics and Communication Engineering',
    lines: ['Learn from Yesterday,', 'Live for Today, and', 'Hop for Tomorrow'],
    heading: 'I BUILD FAST, SCALABLE WEB APPS',
    subtext: 'Full-stack development with a focus on performance and user experience.',
  },
  testimonials: [
    {
      name: 'Sarah Chen',
      role: 'Tech Lead, InnovateLabs',
      feedback: 'Highly skilled developer, delivered fast and clean code. Excellent problem-solving ability and communication throughout the project.',
      rating: 5,
      avatar: '/img/avatars/avatar-1.svg',
    },
    {
      name: 'Marcus Johnson',
      role: 'Startup Founder',
      feedback: 'Great developer who understood our vision immediately. Built scalable solutions with excellent performance.',
      rating: 5,
      avatar: '/img/avatars/avatar-2.svg',
    },
    {
      name: 'Emily Rodriguez',
      role: 'Project Manager',
      feedback: 'Exceptional work ethic and technical skills. Delivered ahead of schedule with exceptional quality.',
      rating: 5,
      avatar: '/img/avatars/avatar-3.svg',
    },
  ],
  featuredProject: {
    title: 'E-Commerce Platform',
    description: 'A real-time e-commerce platform with inventory management, payment processing, and analytics dashboard.',
    problem: 'Slow, outdated website with poor mobile experience and no real-time inventory tracking.',
    solution: 'Built a modern React-based frontend with Node.js backend, integrated Stripe payments, and real-time WebSocket updates.',
    techStack: ['React', 'Node.js', 'MongoDB', 'Stripe', 'WebSocket'],
    image: '/img/projects/ecommerce.png',
    liveDemo: 'https://example.com',
    github: 'https://github.com',
  },
  summary:
    'Passionate full-stack developer focused on building fast, scalable web applications. I turn complex problems into elegant solutions with clean code and modern tech.',
  education: [
    {
      degree: 'B.E / Electronics and Communication Engineering',
      school: 'Study World College of Engineering (Anna University)',
      years: '2022 - 2026',
      score: 'CGPA: 7.8 / 10',
    },
    {
      degree: 'HSC',
      school: 'Shree B.C.R Mat Hr Sec School, Dharmapuri.',
      years: '2020 - 2022',
      score: 'Percentage: 57 / 100',
    },
    {
      degree: 'SSLC',
      school: 'Government Secondary School, Hosur.',
      years: '2019 - 2020',
      score: 'Percentage: 50 / 100',
    },
  ],
  skills: {
    frontend: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Figma'],
    backend: ['Node.js', 'Express', 'MongoDB', 'PostgreSQL', 'REST APIs'],
    tools: ['Git', 'GitHub', 'VS Code', 'Docker', 'AWS'],
  },
  skillLogos: [
    '/img/logo/html.png',
    '/img/logo/css.png',
    '/img/logo/js.png',
    '/img/logo/figma.png',
    '/img/logo/canva.png',
    '/img/logo/ps.png',
    '/img/logo/c++.png',
    '/img/logo/Python.png',
    '/img/logo/ard.png',
    '/img/logo/pi.png',
    '/img/logo/git.png',
    '/img/logo/github.png',
  ],
  gallery: [
    '/img/Img Cer/cer.01.jpg',
    '/img/Img Cer/cer.02.jpg',
    '/img/Img Cer/cer.03.jpg',
    '/img/Img Cer/cer.04.jpg',
    '/img/Img Cer/cer.05.jpg',
    '/img/Img Cer/cer.06.jpg',
    '/img/Img Cer/cer.07.jpg',
    '/img/Img Cer/cer.08.jpg',
  ],
  projects: [
    {
      title: 'Personal Portfolio Website',
      description: 'Responsive portfolio showcase using HTML, CSS, JavaScript.',
      techStack: ['HTML', 'CSS', 'JavaScript'],
      image: '/img/projects/portfolio.png',
      github: 'https://github.com',
    },
    {
      title: 'YouTube Clone',
      description: 'Front-end design mirroring YouTube layout.',
      techStack: ['HTML5', 'CSS3'],
      image: '/img/projects/youtube.png',
      github: 'https://github.com',
    },
    {
      title: 'FootStep Power Generator',
      description: 'IoT model converting mechanical energy to electrical.',
      techStack: ['Arduino', 'Piezoelectric'],
      image: '/img/projects/footstep.png',
      github: 'https://github.com',
    },
    {
      title: 'Smart Vacuum Cleaner',
      description: 'IoT vacuum with obstacle detection.',
      techStack: ['Arduino', 'Sensors'],
      image: '/img/projects/vacuum.png',
      github: 'https://github.com',
    },
  ],
  contact: {
    email: '052005hari@gmail.com',
    phone: '+91 7200550619',
    linkedin: 'https://www.linkedin.com/in/mrnobody1305',
    github: 'https://github.com/MrNobody7200',
    discord: 'xxxxxxx#0000',
    resume: '/Doc/Hariharan.pdf',
  },
  terminal: {
    user: 'hariharan',
    hostname: 'dev-portfolio',
    whoami: 'Full-stack Developer | React | Node.js | IoT Enthusiast',
    stack: [
      { category: 'Frontend', items: ['React', 'Next.js', 'TypeScript', 'Tailwind'] },
      { category: 'Backend', items: ['Node.js', 'Express', 'MongoDB'] },
      { category: 'Tools', items: ['Git', 'Docker', 'AWS'] },
    ],
  },
};